# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stacks | Stack Overflow
description: The UI pattern library for the Stack Overflow, Stack Overflow Carers, and the Stack Exchange Network.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://stackexchange.github.io/stacks-ui/ # the base hostname & protocol for your site

# Build settings
markdown: kramdown

lib: assets
img: assets/images
css: assets/stylesheets
js: assets/javascripts

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, docs-*.html, .asset-cache]

permalink: pretty