assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .asset-cache

gems:
  - jekyll-assets
  - jekyll-contentblocks

name: site_name

permalink: pretty

url: http://stackexchange.github.io/stacks/
